package:
  name: supercron
  version: 1.0.0

source:
  path: .

build:
  noarch: python
  number: 0
  script: python setup.py install

requirements:
  build:
    - setuptools
    - python

  run:
    - python

test:
  imports:
    - supercron

about:
  home: https://github.com/tazimmerman/supercron
  license: GNU GPL 3.0
  description: |
    supervisord plugin to start & start processes using a crontab-like schedule
